name: Deploy to Netlify

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Netlify prod
        run: |
          netlify deploy --prod \
            --dir=. \
            --site ${{ secrets.NETLIFY_API_TOKEN }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} 
